# Generated by Django 3.2.9 on 2022-01-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker2', models.TextField()),
                ('category_name', models.CharField(max_length=40, verbose_name='카테고리이름')),
                ('category_ticker', models.CharField(max_length=40, verbose_name='카테고리티커')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('stock_price', models.IntegerField(null=True, verbose_name='주식 가격')),
                ('market', models.CharField(choices=[('p', 'Kospi'), ('d', 'Kosdaq'), ('n', 'Nasdaq')], max_length=1, verbose_name='마켓')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarters', models.CharField(max_length=40, verbose_name='분기')),
                ('years', models.CharField(max_length=40, verbose_name='년')),
                ('sales', models.IntegerField(verbose_name='총 매출')),
                ('net_profit', models.CharField(max_length=40, verbose_name='순이익')),
                ('ticker4', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='scraping.company', verbose_name='티커')),
            ],
        ),
    ]
