# Generated by Django 3.2.9 on 2022-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker3', models.TextField()),
                ('result', models.CharField(max_length=200, verbose_name='총거래')),
            ],
        ),
    ]
